import 'dart:convert';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class Deck {
  String id;
  String name;
  Map<String, int> cards;
  DateTime lastUpdated;

  Deck({
    required this.id,
    required this.name,
    required this.cards,
    required this.lastUpdated,
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'name': name,
        'cards': cards,
        'lastUpdated': lastUpdated.toIso8601String(),
      };

  factory Deck.fromJson(Map<String, dynamic> json) {
    DateTime parseDate;
    if (json['lastUpdated'] is Timestamp) {
      parseDate = (json['lastUpdated'] as Timestamp).toDate();
    } else {
      parseDate = DateTime.parse(
          json['lastUpdated'] ?? DateTime.now().toIso8601String());
    }
    return Deck(
      id: json['id'],
      name: json['name'],
      cards: Map<String, int>.from(json['cards'] ?? {}),
      lastUpdated: parseDate,
    );
  }
}

class DeckProvider with ChangeNotifier {
  List<Deck> _decks = [];
  String? _currentEditingDeckId;
  User? _user;
  StreamSubscription? _authSubscription;

  List<Deck> get decks => _decks;
  Deck? get currentDeck => _currentEditingDeckId == null
      ? null
      : _decks.firstWhere((d) => d.id == _currentEditingDeckId,
          orElse: () => _decks.first);

  DeckProvider() {
    _init();
  }

  void _init() {
    _authSubscription =
        FirebaseAuth.instance.authStateChanges().listen((firebaseUser) {
      _user = firebaseUser;
      if (firebaseUser != null) {
        _loadDecksFromCloud();
      } else {
        _loadDecksFromLocal();
      }
    });
  }

  @override
  void dispose() {
    _authSubscription?.cancel();
    super.dispose();
  }

  // --- 【核心：智慧切分邏輯】 ---
  // 用來處理像 S-P-098/M-P 這種擴充包與卡號都帶橫線的情況
  List<String> _smartSplit(String fullId, Map<String, dynamic> database) {
    List<String> allParts = fullId.split('-');

    // 從左往右嘗試組合橫線，直到在資料庫中找到匹配的 SetCode
    for (int i = 1; i < allParts.length; i++) {
      String potentialSet = allParts.sublist(0, i).join('-');
      if (database.containsKey(potentialSet)) {
        String cNum = allParts.sublist(i).join('-'); // 剩下的就是卡號
        return [potentialSet, cNum];
      }
    }

    // 如果找不到匹配（防呆），則退回第一個橫線切分
    int firstDash = fullId.indexOf('-');
    if (firstDash == -1) return [fullId, ""];
    return [fullId.substring(0, firstDash), fullId.substring(firstDash + 1)];
  }

  // --- 導出功能 ---
  String generateExportText(Deck deck, Map<String, dynamic> database) {
    StringBuffer buffer = StringBuffer();
    buffer.writeln("【PTCG 牌組：${deck.name}】");
    int total = deck.cards.values.fold(0, (sum, c) => sum + c);
    buffer.writeln("📋 總張數：$total / 60\n");

    List<String> pokemons = [];
    List<String> trainers = [];
    List<String> energies = [];
    List<String> others = [];

    deck.cards.forEach((fullId, count) {
      // 使用智慧切分
      final parts = _smartSplit(fullId, database);
      final sCode = parts[0];
      final cNum = parts[1];

      final cardData = database[sCode]?['cards']?[cNum];

      if (cardData != null) {
        String name = cardData['name'] ?? "未知";
        String rarity = cardData['rarity'] ?? "";
        String type = (cardData['type'] ?? "").toString();
        String line = "• [$sCode] $name ($rarity) x$count";

        if (type == "寶可夢")
          pokemons.add(line);
        else if (type == "訓練家")
          trainers.add(line);
        else if (type == "能量")
          energies.add(line);
        else {
          if (name.contains("能量"))
            energies.add(line);
          else
            others.add(line);
        }
      }
    });

    if (pokemons.isNotEmpty) {
      buffer.writeln("▼ 寶可夢 (${pokemons.length} 種)\n${pokemons.join('\n')}\n");
    }
    if (trainers.isNotEmpty) {
      buffer.writeln("▼ 訓練家 (${trainers.length} 種)\n${trainers.join('\n')}\n");
    }
    if (energies.isNotEmpty) {
      buffer.writeln("▼ 能量 (${energies.length} 種)\n${energies.join('\n')}\n");
    }
    if (others.isNotEmpty) {
      buffer.writeln("▼ 其他\n${others.join('\n')}\n");
    }

    buffer.writeln("---\nGenerated by PokeScan TW");
    return buffer.toString();
  }

  // --- 編輯功能 ---
  String? addCardToDeck(
      String fullId, String cardName, Map<String, dynamic> database) {
    final deck = currentDeck;
    if (deck == null) return "請先選擇牌組";

    int totalCount = deck.cards.values.fold(0, (sum, count) => sum + count);
    if (totalCount >= 60) return "牌組已滿 60 張";

    // 1. 使用智慧切分取得目前的卡片資訊
    final parts = _smartSplit(fullId, database);
    var cardData = database[parts[0]]?['cards']?[parts[1]];
    String regMark = (cardData?['reg'] ?? "").toString().toUpperCase();

    // 2. 判斷是否為基本能量 (不限 4 張)
    bool isBasicEnergy = (regMark == "NONE") ||
        (cardName.startsWith("基本") && cardName.endsWith("能量"));

    if (!isBasicEnergy) {
      int nameCount = 0;
      deck.cards.forEach((existingId, count) {
        // 3. 重要：檢查牌組內已有卡片時，也要用智慧切分來對比名稱
        final eParts = _smartSplit(existingId, database);
        String? existingName =
            database[eParts[0]]?['cards']?[eParts[1]]?['name'];
        if (existingName == cardName) nameCount += count;
      });

      if (nameCount >= 4) return "同名卡片「$cardName」最多只能放 4 張";
    }

    deck.cards[fullId] = (deck.cards[fullId] ?? 0) + 1;
    deck.lastUpdated = DateTime.now();
    _saveDecksToLocal();
    _syncSingleDeckToCloud(deck);
    notifyListeners();
    return null;
  }

  void removeCardFromDeck(String fullId) {
    final deck = currentDeck;
    if (deck == null || !deck.cards.containsKey(fullId)) return;
    if (deck.cards[fullId]! > 1) {
      deck.cards[fullId] = deck.cards[fullId]! - 1;
    } else {
      deck.cards.remove(fullId);
    }
    deck.lastUpdated = DateTime.now();
    _saveDecksToLocal();
    _syncSingleDeckToCloud(deck);
    notifyListeners();
  }

  // --- 同步與持久化 ---
  Future<void> _loadDecksFromLocal() async {
    final prefs = await SharedPreferences.getInstance();
    final String? data = prefs.getString('user_decks');
    _decks = (data != null)
        ? (json.decode(data) as List).map((d) => Deck.fromJson(d)).toList()
        : [];
    notifyListeners();
  }

  Future<void> _loadDecksFromCloud() async {
    if (_user == null) return;
    try {
      final snapshot = await FirebaseFirestore.instance
          .collection('users')
          .doc(_user!.uid)
          .collection('decks')
          .get();
      if (snapshot.docs.isNotEmpty) {
        _decks = snapshot.docs.map((doc) => Deck.fromJson(doc.data())).toList();
        _saveDecksToLocal();
      } else {
        await _loadDecksFromLocal();
        for (var deck in _decks) {
          _syncSingleDeckToCloud(deck);
        }
      }
      notifyListeners();
    } catch (e) {
      _loadDecksFromLocal();
    }
  }

  Future<void> _syncSingleDeckToCloud(Deck deck) async {
    if (_user == null) return;
    try {
      await FirebaseFirestore.instance
          .collection('users')
          .doc(_user!.uid)
          .collection('decks')
          .doc(deck.id)
          .set(deck.toJson());
    } catch (e) {
      print("❌ 雲端同步失敗");
    }
  }

  void createDeck(String name) {
    final newDeck = Deck(
        id: DateTime.now().millisecondsSinceEpoch.toString(),
        name: name,
        cards: {},
        lastUpdated: DateTime.now());
    _decks.add(newDeck);
    _currentEditingDeckId = newDeck.id;
    _saveDecksToLocal();
    _syncSingleDeckToCloud(newDeck);
    notifyListeners();
  }

  void deleteDeck(String id) {
    _decks.removeWhere((d) => d.id == id);
    if (_currentEditingDeckId == id) _currentEditingDeckId = null;
    _saveDecksToLocal();
    if (_user != null)
      FirebaseFirestore.instance
          .collection('users')
          .doc(_user!.uid)
          .collection('decks')
          .doc(id)
          .delete();
    notifyListeners();
  }

  void selectDeck(String? id) {
    _currentEditingDeckId = id;
    notifyListeners();
  }

  Future<void> _saveDecksToLocal() async {
    final prefs = await SharedPreferences.getInstance();
    prefs.setString(
        'user_decks', json.encode(_decks.map((d) => d.toJson()).toList()));
  }
}
