// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTzkvRIlAfjw5B_YC2Vqi0RjOY-9w8jMQ',
    appId: '1:755806773470:web:ba33e4f52aec636867a24f',
    messagingSenderId: '755806773470',
    projectId: 'pokescan-tw',
    authDomain: 'pokescan-tw.firebaseapp.com',
    storageBucket: 'pokescan-tw.firebasestorage.app',
    measurementId: 'G-FMG2QYFBPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaeSlVZB6nuGGd0ilH7WzYPYbM27DMhTA',
    appId: '1:755806773470:android:41b8c05f2704659d67a24f',
    messagingSenderId: '755806773470',
    projectId: 'pokescan-tw',
    storageBucket: 'pokescan-tw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvPFw1nz8qAo8e7QZtCtF_h6h7GyHZvNM',
    appId: '1:755806773470:ios:be11eabd700d769b67a24f',
    messagingSenderId: '755806773470',
    projectId: 'pokescan-tw',
    storageBucket: 'pokescan-tw.firebasestorage.app',
    iosBundleId: 'com.example.pokeScanTw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvPFw1nz8qAo8e7QZtCtF_h6h7GyHZvNM',
    appId: '1:755806773470:ios:be11eabd700d769b67a24f',
    messagingSenderId: '755806773470',
    projectId: 'pokescan-tw',
    storageBucket: 'pokescan-tw.firebasestorage.app',
    iosBundleId: 'com.example.pokeScanTw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTzkvRIlAfjw5B_YC2Vqi0RjOY-9w8jMQ',
    appId: '1:755806773470:web:6f49d5f5dc0d22f467a24f',
    messagingSenderId: '755806773470',
    projectId: 'pokescan-tw',
    authDomain: 'pokescan-tw.firebaseapp.com',
    storageBucket: 'pokescan-tw.firebasestorage.app',
    measurementId: 'G-K9EKYSTETH',
  );
}
